config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get 'welcome/ring' => "welcome#ring"

  get 'welcome/show' => 'welcome#show'

  get '/songs/create' => 'songs#create'

  post '/songs/create' => 'songs#create'

  get '/songs/index' => 'songs#index'

end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, :mood, :stream_url, presence: true
  validates :title, :stream_url, uniqueness: true
end

app/models/soundcloud_client.rb
class SoundcloudClient
  attr_reader :client

  def initialize(opts)
    @client = Soundcloud.new(default_options.merge(token_options))
  end

  private


    def default_options
      {
        :client_id     => CLIENT.client_id,
        :client_secret => CLIENT.client_secret,
      }
    end

    def token_options
      {
        :expires_at    => soundcloud_expires_at,
        :access_token  => soundcloud_access_token,
        :refresh_token => soundcloud_refresh_token
      }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  respond_to :html, :js

  def create
    Song.create(title: params[:title], stream_url: params[:stream_url], mood: params[:mood], track_id: params[:track_id], permalink_url: params[:permalink_url])
    redirect_to root_path
  end

  def index
    @songs = Song.where(mood: params[:mood])
    respond_to do |format|
      format.js {render :json => @songs}
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def ring
    render :partial => "ring"
  end

  def index
  end

  def show
    @mood = params[:mood]
    render :show
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    @current_user = user
    session[:current_user_id] = user.try(:id)
  end

  def logged_in?
    !!@current_user
  end  

  def logout
    session.delete(:current_user_id)
    @current_user = nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoodRing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Telex' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Varela" rel="stylesheet" type="text/css"/>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js" type="text/javascript"></script>
  <script src="https://connect.soundcloud.com/sdk-2.0.0.js"></script>
  <script>
  SC.initialize({
    client_id: "e67d17cea5de0deead27fed93e338691",
  });
  </script>

  <script type="x-shader/x-vertex" id="vertexshader">

    attribute float size;
    attribute vec3 pcolor;
    varying vec3 vColor;
    void main() {
      vColor = pcolor;
      vec4 mvPosition = modelViewMatrix * vec4( position, 1.0 );
      gl_PointSize = size * ( 200.0 / length( mvPosition.xyz ) );
      gl_Position = projectionMatrix * mvPosition;
    }
  </script>

  <script type="x-shader/x-fragment" id="fragmentshader">
    uniform sampler2D texture;
    varying vec3 vColor;
    void main() {
      vec4 outColor = texture2D( texture, gl_PointCoord );
      gl_FragColor = outColor * vec4( vColor, 1.0 );
    }
  </script>

</head>
<body class="<%= controller_name %> <%= action_name %>">
  <%= yield %>
</body>

</html>

app/views/users/callback.html.erb
<!DOCTYPE html>
<html lang="en">
  <head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Connect with SoundCloud</title>
  </head>
  <body onload="window.opener.setTimeout(window.opener.SC.connectCallback, 1)">
    <b style="width: 100%; text-align: center;">This popup should automatically close in a few seconds</b>
  </body>
</html>

app/views/welcome/_homepage.html.erb
<div id="big-ring" class="slide">
  <h1 id = 'homepage'>mood ring</h1>
  <div class="glowing-ring happy"  data-mood="Happy"><h3 id="mood-text"><%= link_to 'happy', welcome_show_path(:mood => "Happy") %></h3></div></a>
  <div class="glowing-ring melancholy" data-mood="Melancholy" ><h3 id="mood-text"><%= link_to 'sad', welcome_show_path(:mood => "Melancholy") %></h3></div></a>
  <div class="glowing-ring excited"  data-mood="Excited" ><h3 id="mood-text"><%= link_to 'excited', welcome_show_path(:mood => "Excited") %></h3></div></a>
  <div class="glowing-ring chill" data-mood="Chill" ><h3 id="mood-text"><%= link_to 'chill', welcome_show_path(:mood => "Chill") %></h3></div></a>
  <div class="glowing-ring angry"  data-mood="Angry" > <h3 id="mood-text"><%= link_to 'angry', welcome_show_path(:mood => "Angry") %></h3></div></a>
  <div class="glowing-ring sleepy" data-mood="Sleepy" ><h3 id="mood-text"><%= link_to 'sleepy', welcome_show_path(:mood => "Sleepy") %></h3></div></a>
</div>

app/views/welcome/index.html.erb
<div id = "home">
	<%= render(:partial => 'homepage') %>
</div>

app/views/welcome/show.html.erb
<%= content_tag :div, class: "current_mood", data: {mood: @mood} do %>
<% end %>

<div id = "visualizer">
  <div>
    <a href="#" id="enterSong" class="slide" title="Search For A Song"><%= image_submit_tag("search-12-32.png", class: "mood-control") %></a>
  </div>

  <div>
    <a href = '#'><%= image_submit_tag('mood_ring.png', id: 'chooseMood', class: 'slide') %></a>

  </div>

  <div id="three"></div>

  <div id="playlist">

    <div id="progressBar"></div>

    <h3 id= "track-title"></h3>

    <div id="all-controls">
      <a id="play" href="#">
        <%= image_submit_tag("play-24.png", class: "player-control") %>
      </a>
      <a id="pause"  href = "#">
        <%= image_submit_tag("pause-24.png", class: "player-control") %>
      </a>
      <a id="next"  href = "#">
        <%= image_submit_tag("arrow-31-24.png", class: "player-control") %>
      </a>
    </div>

  <img src="/assets/soundcloud.png" id = "soundcloud">

</div>


<div class="slide inputSlides" id="inputSong">
  <a href="#" class="hide" id ="close"><img src='/assets/x-mark-3-16.png'></a>
  <h1>Search Soundcloud</h1>
  <h3> to add song to Mood Ring</h3>
  <form id = "input" method = "get">
  <input id="titleSearch" type="text" placeholder= "song title, artist, tag, etc." autocomplete= 'off'>
  </form>
  <div id= "search-error"></div>
</div>

<div class="slide inputSlides" id="addSong">
   <ul class="exitGoBack">
    <li id = "with-hide-class"><a href="#" class="hide"><img src='/assets/x-mark-3-16.png'></a></li>
    <li id = "going-back"><a href="#" class="goBack" id="toFirstSlide"><img src='/assets/arrow-58-16.png'></a></li>
  </ul>
  <h1>Choose a song to add</h1>
  <div id = 'songList'></div>
</div>

<div class="slide inputSlides" id="songMood">
   <ul class="exitGoBack">
    <li><a href="#" class="hide"><img src='/assets/x-mark-3-16.png'></a></li>
    <li><a href="#" class="goBack" id="toSecondSlide"><img src='/assets/arrow-58-16.png'></a></li>
  </ul>
  <h1>What mood describes this song?</h1>
  <button class="moodChoice" id="Happy"><%= link_to 'Happy', welcome_show_path(:mood => "Happy") %></button>
  <button class="moodChoice" id="Melancholy"><%= link_to 'Melancholy', welcome_show_path(:mood => "Melancholy") %></button>
  <button class="moodChoice" id="Excited"><%= link_to 'Excited', welcome_show_path(:mood => "Excited") %></button>
  <button class="moodChoice" id="Chill"><%= link_to 'Chill', welcome_show_path(:mood => "Chill") %></button>
  <button class="moodChoice" id="Angry"><%= link_to 'Angry', welcome_show_path(:mood => "Angry") %></button>
  <button class="moodChoice" id="Sleepy"><%= link_to 'Sleepy', welcome_show_path(:mood => "Sleepy") %></button>
</div>


<%= render(:partial => 'homepage') %>